services:
  - type: web
    name: ml-model-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ml-dashboard-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: API_KEY_SECRET
        generateValue: true
    autoDeploy: false

databases:
  - name: ml-dashboard-db
    databaseName: ml_dashboard
    user: ml_user
    plan: free